### ISSUE TITLE
error when doing just all / just build-wallet / just build-examples

### ISSUE THREAD

**Issue by silkroadnomad** [PeerPiper/peerpiper#3]
When doing ```just all``` I receive : 

error: no such command: `component`

same with  just build-wallet / just build-examples

I am new to just and rust - component command of cargo is missing. 

I did: 
cargo search cargo-component
cargo install cargo-component
to fix the issue.

This is probably not project-related. So in case it is Rust related please close the issue.

**Comment by DougAnderson444** [comment]
This is setup related. I added the requirement for [`cargo-component`](https://github.com/bytecodealliance/cargo-component) in the docs too
