### ISSUE TITLE
just all error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by silkroadnomad** [PeerPiper/peerpiper#4]
When running ```just all``` the process stopped due "error[internal]: left behind trailing whitespace".
I found a related issue: https://github.com/planus-org/planus/issues/167 to run rustfmt twice to remove the white spaces.
I used the following script
```
find . -name '*.rs' -exec rustfmt --edition 2021 '{}' +
find . -name '*.rs' -exec rustfmt --edition 2021 --config max_width=1000 
```

but had to remove a whitespace in seed-keeper-wallet/src/lib/ line: 40 manually to fix the issue

**Comment by DougAnderson444** [comment]
I just got this same issue! After updating to `cargo-component` v0.9.0

**Comment by DougAnderson444** [comment]
This is an upstream issue with `cargo-component` which is patched in https://github.com/bytecodealliance/cargo-component/pull/247 

Just waiting for a release patch to `v0.9.1` for this is disappear
